version: '3.4'
services:
 mongodb:
  container_name: mongo
  image: mongo:latest
  ports:
   - 27017:27017
  volumes:
   - my-mongo-volume:/data/db
  networks: 
   - node-mongo-network

 starb2w:
   build:
    dockerfile: ./Dockerfile
    context: .
   ports:
    - 3800:3800
   links:
    - mongodb
   restart: on-failure
   networks: 
     - node-mongo-network
   depends_on:
    - mongodb

volumes:
  my-mongo-volume:

networks: 
  node-mongo-network:
    driver: bridge

